# Generated by Django 2.2.9 on 2020-02-01 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eveonline', '0010_alliance_ticker'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expires', models.IntegerField()),
                ('link_ref', models.CharField(max_length=20)),
                ('creator', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eveonline.EveCharacter')),
            ],
            options={
                'permissions': (('create_new_links', 'Can Create Temp Links'),),
            },
        ),
    ]
