# Generated by Django 4.2.28 on 2026-03-12 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("eveonline", "0017_alliance_and_corp_names_are_not_unique"),
        ("mumbletemps", "0006_tempuser_character_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="templink",
            name="creator",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="eveonline.evecharacter",
            ),
        ),
    ]
