name: Deploy to PyPi

on:
  release:
    types: [released, prereleased]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Clean up environment
        run: make clean

      - name: Build package
        run: make build

      - name: Upload Package to PyPi
        if: ${{ !env.ACT }} # Don't run in a local test environment
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: make deploy
